### ISSUE TITLE
How to get rectangular outline on custom activity?

### ISSUE THREAD

**Issue by kiaanpillay** [BlinkID/blinkid-android#25] opened 2017-01-19 14:12 UTC
When scanning a PDF417 in the default activity it creates a rectangular outline in the ui to show the user where it is currently scanning, how am I able to get this with a custom activity?

**Comment by culoi** [comment] 2017-01-30 16:21
Closed as an exact duplicate of https://github.com/PDF417/pdf417-android/issues/24

**Closed by culoi** 2017-01-30 16:21 UTC
