### ISSUE TITLE
Unable to scan Barcode or Passport on Vivo V9. Able to scan Malaysian MyKad

### ISSUE THREAD

**Issue by tjwoon** [BlinkID/blinkid-android#121] opened 2018-08-21 09:31 UTC
### Description

Unable to scan passport or barcode. The BlinkID activity just remains on screen without returning a result.

Able to scan Malaysian MyKad.

### Environment Details

**BlinkID version:** 3.16.0

**Device model:** Vivo V9

**Device ABI (processor architecture, e.g. ARMv7):** ARM

### Additional information

The same app and SDK version is able to scan passports and barcodes on other devices.

**Comment by i1E** [comment] 2018-08-21 11:45
Hi @tjwoon,

please upgrade to latest version of the BlinkID (v4.1.0), we have new API which is more powerful and simpler, with a lot of new features.

If you want to scan barcode, you have to activate `BarcodeRecognizer`. To scan Passport, you should use `MrtdRecognizer`. Add them to the recognizer list when configuring the recognition settings.

**Comment by tjwoon** [comment] 2018-08-21 12:27
Hi @i1E

Is there any reason v3.16.0 should not work? To upgrade to v4 will require time as it is not nackwards conpatible

**Comment by i1E** [comment] 2018-08-21 12:34
Hi @tjwoon,

v3.16.0 should work, but in long term it is recommended to upgrade to new API because new features will not be available on the old API. 

Can you please explain exactly which passports and barcodes you are trying to scan. There are specialised recognizers for various document types. If you have activated only MyKadRecognizer, it is expected that Passports and Barcodes won't be scanned, because you haven't activated corresponding recognizers for these document types. In our repository there is a project with [sample apps](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample) where you can find useful code snippets.

**Comment by hockleongloh** [comment] 2018-08-27 03:16
Hi @i1E We did activate the BarcodeRecognizer and when scanning barcode and MrtdRecognizer for passport. However still facing the same issue that @tjwoon mentioned above

**Comment by culoi** [comment] 2018-08-27 11:38
Hello,

Can you please share the sample of the document and the barcode that you are scanning? Also, are you able to use another device just to make sure that the issue isn't in the device camera or implementation settings? 

Regards

**Comment by culoi** [comment] 2018-09-11 10:03
Closing the issue, please reopen if you have additional questions or contact us directly at support@microblink.com

**Closed by culoi** 2018-09-11 10:03 UTC
