### ISSUE TITLE
BlinkIDImageListenerDemo immediately crashes

### ISSUE THREAD

**Issue by tonyteate** [BlinkID/blinkid-android#15] opened 2016-11-08 10:47 UTC
We also filed a support ticket, but opening an issue here as well out of urgency. From the support ticket:

> We are having trouble integrating the BlinkID Android SDK into our project.
> 
> Specifically, we are unable to integrate the ability to scan MRTD documents into our application. The demo project, BlinkIDImageListenerDemo [1], included in the GitHub repository continuously crashes before any scanning can be completed.
> 
> Attached is a log file from a session of attempting to run the aforementioned project. [1]
> 
> We sincerely appreciate any immediate help you can offer towards this integration issue, as we are short on time to complete this integration.

Specifically, when I run the BlinkIDImageListenerDemo, the launch screen has a single button on it that says "Scan MRTD". Upon clicking that button, the ScanCard Activity is started and, after a few seconds of seemingly trying to autofocus, just closes (taking me back to the first screen). The app does not crash completely, but there do appear to be error related messages in the log output file that I attached.

Also, Info on the device we are having issues with (from the suggested app [2]):

Manufacturer - Motorola
Model - XT1096
Hardware - qcom
Board - MSM8974
Device - victara

[1]  https://play.google.com/store/apps/details?id=com.jphilli85.deviceinfo&hl=en
[2] https://microblink.zendesk.com/attachments/token/3xtobspIZ7TbcAXOncdTTRywB/?name=logs_201611080229.txt

**Comment by tonyteate** [comment] 2016-11-10 18:38
[Video of the problem for reference](https://microblink.zendesk.com/attachments/token/w3Ie5qguId1mLVv4Ze3h21joh/?name=device-2016-11-08-100419.mp4) 

If anyone else is running into this similar issue, turning off frame quality estimation is a stopgap, but still awaiting a fix:

settings.setFrameQualityEstimationMode(RecognitionSettings.FrameQualityEstimationMode.ALWAYS_OFF);

**Comment by DoDoENT** [comment] 2016-11-10 18:51
Hi @tonyteate. We managed to reproduce the problem on [HTC One SV](http://www.gsmarena.com/htc_one_sv-5105.php) and are still looking out what went wrong. It appears that on most devices crash does not happen at all.

Also thank you for the frame quality estimation tip. It will help us track down the problem.

**Comment by DoDoENT** [comment] 2016-11-11 15:38
Hi @tonyteate!

Good news! We managed to fix the problem internally. The fix will be released with new version of BlinkID.

**Comment by tonyteate** [comment] 2016-11-11 17:53
@DoDoENT Great to hear! Looking forward to updating to the new version soon.

**Comment by DoDoENT** [comment] 2016-11-14 12:19
Hi @tonyteate,

please check if the issue has been solved in [v3.2.0](https://github.com/BlinkID/blinkid-android/releases/tag/v3.2.0).

If the issue is solved, please close it.

**Closed** 2016-11-30 03:49 UTC
