### ISSUE TITLE
Camera fails to resume after multiple onPause, and shows black screen.

### ISSUE THREAD

**Issue by passid2019** [BlinkID/blinkid-android#215] opened 2020-06-26 12:16 UTC
### Description

Camera fails to resume after onPause, shows black screen. This issue is also on live microblink vision app on the store. The camera will resume only if onPause and OnResume was triggered again by locking and unlocking the phone, or by activity restarted.

### Environment Details

**BlinkID version: 5.5.0

**Device model: Samsung A70

**Device Android version: 10

**Comment by SandraKuzmic** [comment] 2020-06-26 12:25
Hi, 

It would help if You could explain the problem a little, can You send us steps to reproduce the bug on the Microblink Vision app? 

Best regards,
Sandra

**Comment by passid2019** [comment] 2020-06-27 05:28
Hey Sandra, 
Steps to reproduce:
1- Open Microblink Vision app
2- Choose worldwide documents.
3- When the camera starts previewing, lock the phone.
4- Unlock the phone.

Expected 
Camera should resume preview, and starts scanning.

Actual 
Camera displays a black screen and doesn't resume unless we lock and unlock the phone again, Sometimes it takes multiple times of locking and unlocking and sometime it works instantly.

**Comment by matvidako** [comment] 2020-06-29 08:00
Hi,

thanks for the repro steps. 
We can't reproduce it exactly like you do but we've managed to reproduce it by letting the screen timeout and then unlocking it.
We'll let you know when we fix it.

**Comment by hossein114** [comment] 2020-09-21 10:21
It also rises in the scanning page we get a phone call, so when we come back to the scan page we see a dark page.

**Comment by anjapenic** [comment] 2021-03-30 10:58
Hello @passid2019 and @hossein114,

We wanted to let you know that the issue was fixed in v5.6.0, we've had several releases since then and would like to know if you tried testing the newest version - v5.10.0 and seeing if the scanning process works as expected? 

Regards,
Anja

**Comment by passid2019** [comment] 2021-04-10 11:40
@anjapenic We have pumped our version to v.5.6.0 quite a while ago and we haven't noticed it since. So i believe everything is working as expected.

**Comment by anjapenic** [comment] 2021-06-02 07:23
Hello @passid2019,

Thanks for the feedback, in that case, we're closing this issue. If you need any further assistance feel free to open a new one or contact us at support@microblink.com.

Best regards,
Anja

**Closed by anjapenic** 2021-06-02 07:23 UTC
